// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutrInfo.Admin.Api.Infrastructure.Database.DataModel;

namespace NutrInfo.Admin.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nutrinfo")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Complement")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Evaluations.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BedNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiseaseSeverity")
                        .HasColumnType("integer");

                    b.Property<float>("Energy")
                        .HasColumnType("real");

                    b.Property<bool>("HasAmputatedLimb")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAscites")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasEdema")
                        .HasColumnType("boolean");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Imc")
                        .HasColumnType("real");

                    b.Property<bool>("IsWalking")
                        .HasColumnType("boolean");

                    b.Property<int>("NutritionState")
                        .HasColumnType("integer");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NutritionistId");

                    b.HasIndex("PatientId");

                    b.ToTable("evaluation");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Crn")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Crn")
                        .IsUnique();

                    b.ToTable("nutritionist");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("UserId");

                    b.ToTable("patient");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BirhDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Evaluations.Evaluation", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", "Nutritionist")
                        .WithMany("Evaluations")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", "Patient")
                        .WithMany("Evaluations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Nutritionist")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
