// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutrInfo.Admin.Api.Infrastructure.Database.DataModel;

#nullable disable

namespace NutrInfo.Admin.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nutrinfo")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amputatedlimbs", b =>
                {
                    b.Property<int>("AmputatedLimbsId")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluationsId")
                        .HasColumnType("integer");

                    b.HasKey("AmputatedLimbsId", "EvaluationsId");

                    b.HasIndex("EvaluationsId");

                    b.ToTable("amputatedlimbs", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("address", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.AmputatedLimbs.AmputatedLimb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Limb")
                        .HasColumnType("text");

                    b.Property<double>("Percentual")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("amputatedlimb", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Evaluations.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiseaseSeverity")
                        .HasColumnType("integer");

                    b.Property<double?>("Energy")
                        .HasColumnType("double precision");

                    b.Property<bool?>("HasAmputatedLimb")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasAscite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasEdema")
                        .HasColumnType("boolean");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<double?>("Imc")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsWalking")
                        .HasColumnType("boolean");

                    b.Property<int?>("NutritionState")
                        .HasColumnType("integer");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NutritionistId");

                    b.HasIndex("PatientId");

                    b.ToTable("evaluation", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Crn")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Crn")
                        .IsUnique();

                    b.ToTable("nutritionist", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("patient", "nutrinfo");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("user", "nutrinfo");
                });

            modelBuilder.Entity("amputatedlimbs", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.AmputatedLimbs.AmputatedLimb", null)
                        .WithMany()
                        .HasForeignKey("AmputatedLimbsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Evaluations.Evaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Addresses.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Evaluations.Evaluation", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", "Nutritionist")
                        .WithMany("Evaluations")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", "Patient")
                        .WithMany("Evaluations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Nutritionist")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", b =>
                {
                    b.HasOne("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Nutritionists.Nutritionist", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Patients.Patient", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("NutrInfo.Admin.Api.Infrastructure.Database.DataModel.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
