// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutrInfo.Admin.Api.Infrastructure.Database.DataModel;

#nullable disable

namespace Nutrinfo.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230129223836_AddMedicalRecord")]
    partial class AddMedicalRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nutrinfo")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Addresses.Address", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("address", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AmputatedLimbs.AmputatedLimb", b =>
                {
                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("AmputatedLimbPercentageId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("EvaluationId", "PatientId", "AmputatedLimbPercentageId");

                    b.HasIndex("AmputatedLimbPercentageId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Reason");

                    b.ToTable("amputatedlimb", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AmputatedLimbsPercentage.AmputatedLimbPercentage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("amputatedlimbpercentage", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AsciteDegrees.AsciteDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AsciticWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PeripheralEdema")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ascitedegree", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Ascites.Ascite", b =>
                {
                    b.Property<int>("AsciteDegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAsciticWeight")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPeripheralEdema")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("AsciteDegreeId", "EvaluationId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("ascite", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Evaluations.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ArmCircumference")
                        .HasColumnType("double precision");

                    b.Property<double>("ArmMuscleCircumference")
                        .HasColumnType("double precision");

                    b.Property<double>("CalfCircumference")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiseaseSeverity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EdemaWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Imc")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsWalking")
                        .HasColumnType("boolean");

                    b.Property<double>("LostWeightLastThreeMonths")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("NextEvaluation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NutritionalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutritionalStateSeverity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReducedDietaryIntake")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeriouslyIllPatient")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TricepsPleat")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NutritionistId");

                    b.HasIndex("PatientId");

                    b.ToTable("evaluation", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Crn")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Crn")
                        .IsUnique();

                    b.ToTable("nutritionist", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("MedicalRecord")
                        .HasColumnType("integer");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("patient", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Addresses.Address", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Addresses.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AmputatedLimbs.AmputatedLimb", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.AmputatedLimbsPercentage.AmputatedLimbPercentage", "LimbPercentage")
                        .WithMany("AmputatedLimbs")
                        .HasForeignKey("AmputatedLimbPercentageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrinfo.Admin.Domain.Evaluations.Evaluation", "Evaluation")
                        .WithMany("AmputatedLimbs")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrinfo.Admin.Domain.Patients.Patient", "Patient")
                        .WithMany("AmputatedLimbs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("LimbPercentage");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Ascites.Ascite", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.AsciteDegrees.AsciteDegree", "AsciteDegree")
                        .WithMany("Ascites")
                        .HasForeignKey("AsciteDegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrinfo.Admin.Domain.Evaluations.Evaluation", "Evaluation")
                        .WithMany("Ascites")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsciteDegree");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Evaluations.Evaluation", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", "Nutritionist")
                        .WithMany("Evaluations")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrinfo.Admin.Domain.Patients.Patient", "Patient")
                        .WithMany("Evaluations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Nutritionist")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Patients.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AmputatedLimbsPercentage.AmputatedLimbPercentage", b =>
                {
                    b.Navigation("AmputatedLimbs");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.AsciteDegrees.AsciteDegree", b =>
                {
                    b.Navigation("Ascites");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Evaluations.Evaluation", b =>
                {
                    b.Navigation("AmputatedLimbs");

                    b.Navigation("Ascites");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.Navigation("AmputatedLimbs");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
