// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutrInfo.Admin.Api.Infrastructure.Database.DataModel;

#nullable disable

namespace NutrInfo.Admin.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220921135643_AddUpdatedAtAsNull4")]
    partial class AddUpdatedAtAsNull4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nutrinfo")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Addresses.Address", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("address", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Evaluations.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AsciteWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiseaseSeverity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EdemaWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasAscite")
                        .HasColumnType("boolean");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Imc")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsWalking")
                        .HasColumnType("boolean");

                    b.Property<double?>("LostWeightLastThreeMonths")
                        .HasColumnType("double precision");

                    b.Property<string>("NutritionalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReducedDietaryIntake")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeriouslyIllPatient")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NutritionistId");

                    b.HasIndex("PatientId");

                    b.ToTable("evaluation", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Crn")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Crn")
                        .IsUnique();

                    b.ToTable("nutritionist", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("patient", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("user", "nutrinfo");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Addresses.Address", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Addresses.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Evaluations.Evaluation", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", "Nutritionist")
                        .WithMany("Evaluations")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrinfo.Admin.Domain.Patients.Patient", "Patient")
                        .WithMany("Evaluations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Nutritionist")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.HasOne("Nutrinfo.Admin.Domain.Users.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Nutrinfo.Admin.Domain.Patients.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Nutritionists.Nutritionist", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Patients.Patient", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Nutrinfo.Admin.Domain.Users.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Nutritionist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
